### ISSUE TITLE
Installation is failing

### ISSUE THREAD

**Issue by narora1** [Technologicat/pyan#28]
I am trying to install pyan on my Ubuntu 18.04 machine but I am getting the following error - 

```
narora@FR-1603:~/Downloads/Python-3.8.2$ sudo pip install pyan3
Collecting pyan3
  Downloading https://files.pythonhosted.org/packages/1c/00/ddbea36dae59a16a7a3facbcf2a228e36360ce0cde323fd05a078dfb1d43/pyan3-1.0.4.tar.gz (43kB)
    100% |████████████████████████████████| 51kB 1.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-LKOzlG/pyan3/setup.py", line 97
        print("WARNING: Version information not found in '%s', using placeholder '%s'" % (init_py_path, version), file=sys.stderr)
                                                                                                                      ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-LKOzlG/pyan3/

```

**Comment by narora1** [comment]
Looks like I needed to use pip3 because this is a python 3 package. It is working now!

**Comment by Technologicat** [comment]
Yes, `pip3` is correct, glad you got it working!
