### ISSUE TITLE
Calling pyan3 without parametters show error

### ISSUE THREAD

**Issue by edumco** [Technologicat/pyan#36]
### Calling Pyan3 without parameters show error

Normally when we use a CLI without passing parameters the application show the help information:

Error log:
```python
Traceback (most recent call last):
  File "/home/eduardo/git/pyan/venv/bin/pyan3", line 4, in <module>
    __import__('pkg_resources').run_script('pyan3==1.0.5', 'pyan3')
  File "/home/eduardo/git/pyan/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/eduardo/git/pyan/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1451, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/pyan3' not found in metadata at '/home/eduardo/git/pyan/venv/lib/python3.8/site-packages/pyan3-1.0.5.egg-info'
```

**Comment by edumco** [comment]
It was a problem with my enviroment
