### ISSUE TITLE
NameError: name 'Union' is not defined

### ISSUE THREAD

**Issue by JamesPei** [Technologicat/pyan#48]
hello, I tried to install directly(use setup.py), and everything is ok during the process, but when I run, I got this:

Traceback (most recent call last):
  File "/home/xxx/.local/bin/pyan3", line 33, in <module>
    sys.exit(load_entry_point('pyan==1.0.5', 'console_scripts', 'pyan3')())
  File "/home/xxx/.local/bin/pyan3", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/xxx/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/xxx/.local/lib/python3.6/site-packages/pyan-1.0.5-py3.6.egg/pyan/__init__.py", line 26, in <module>
NameError: name 'Union' is not defined

So how can I resolve this?

**Comment by gourrier** [comment]
Same for me, unfortunately...
Running this fork on Python3.6 from Windows command line, I get:

Traceback (most recent call last):
  File "pyan3", line 11, in <module>
    from pyan.pyan import main
  File "c:\Python36\lib\site-packages\pyan\pyan\__init__.py", line 26, in <module>
    grouped: bool = True,
NameError: name 'Union' is not defined

**Comment by dtilchin** [comment]
I got this on Python 3.8; I  switched to 3.9  and it works.

(I've run into several packages lately that exclusively work on 3.8  or 3.9. Bit of a bummer)

**Comment by Technologicat** [comment]
Please try the latest Pyan from this repo in GitHub, the type annotations need some imports (see #42). The latest code works, but the PyPI package hasn't been updated yet.

Thanks for reporting!

**Comment by Technologicat** [comment]
PyPI package `pyan3` updated. Please try again with the latest version, and reopen this issue if necessary.
