### ISSUE TITLE
got multiple values for argument 'root' after upgrade 1.1.1 -> 1.20

### ISSUE THREAD

**Issue by laimaretto** [Technologicat/pyan#79]
Hi! So I upgraded from pyan 1.1.1 to 1.20 and after that, I'm getting the following error:

```
$ pyan3 taskAutom.py --uses --no-defines --colored --grouped --annotated --dot-rankdir LR --html > taskAutom.html
Traceback (most recent call last):
  File "/usr/local/bin/pyan3", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pyan/main.py", line 206, in main
    v = CallGraphVisitor(filenames, logger, root=root)
TypeError: __init__() got multiple values for argument 'root'
```
I could generate the graph for [taskAutom](https://github.com/laimaretto/taskAutom) with version 1.1.1 but I'm not anymore with 1.2.0.

Any hint?

Thanks!

Lucas

**Comment by ani-hovhannisyan** [comment]
I got similar error, every time I run simple pyan3 commands such as following one:
$ pyan3 filename.py --html 
Traceback (most recent call last):
  File "/usr/local/bin/pyan3", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/pyan/main.py", line 206, in main
    v = CallGraphVisitor(filenames, logger=logger, root=root)
  File "/home/user/.local/lib/python3.8/site-packages/pyan/analyzer.py", line 60, in __init__
    mod_name = get_module_name(filename)
  File "/home/user/.local/lib/python3.8/site-packages/pyan/anutils.py", line 40, in get_module_name
    is_root = any([f == "__init__.py" for f in os.listdir(potential_root)])
FileNotFoundError: [Errno 2] No such file or directory: ''
OS: Linux  5.10.0-1045-oem #47-Ubuntu SMP Wed Aug 18 10:41:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Any ideas?

**Comment by mailhost** [comment]
Looks this was fixed in #65

**Comment by z0gSh1u** [comment]
**Workaround:** Using pyan from a Python script doesn't encounter this.

```py
import pyan

callgraph = pyan.create_callgraph('somewhere/**/*.py', format='dot', <other arguments>)

with open('somewhere.dot', 'w') as f:
    f.write(cg)
```

**Comment by jl1011** [comment]
I had to do a tiny bit of editing cause I didn't understand what z0gSh1u meant, but basically:

```
import pyan
    callgraph = pyan.create_callgraph('C:\\PATH\\TO\\YOUR\\FILE\\MAINFOLDER\\*.py', format='html')
    with open('WHAT_YOU_WANT_THE_GRAPH_FILE_TO_BE_CALLED.html', 'w') as f:
        f.write(callgraph)
```
and that, put pretty much anywhere in my code, puts every py file in the folder specified by the path into the graph :)

**Comment by ColtAllen** [comment]
Would it be possible to proceed with publishing the next version release seeing as this issue is now fixed?
