### ISSUE TITLE
CallGraphVisitor wrong parameters

### ISSUE THREAD

**Issue by mhechthz** [Technologicat/pyan#96]
It seems that the library is somewhat outdated. I get with Python 3.11:

```
pyan3 *.py --uses --no-defines --colored --grouped --annotated --svg > callgraph.svg
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\pyan3.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\pyan\main.py", line 206, in main
    v = CallGraphVisitor(filenames, logger, root=root)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CallGraphVisitor.__init__() got multiple values for argument 'root'
```

Seems that there was a change in how to call the function. Is this library still maintained?

**Comment by egoughnour** [comment]
See [Fix wrong arguments for CallGraphVisitor] (https://github.com/Technologicat/pyan/pull/65). 
Also the comments on [got multiple values for ...](https://github.com/Technologicat/pyan/issues/79).
You can install, open line 206 and insert `=logger` so that the second arg becomes a kwarg, i.e., 
`CallGraphVisitor(filenames, logger=logger, root=root)`
Then calling with an absolute path to your glob and setting the `--root` might help.
Anyway this seems to be a non-issue when calling programmatically.  So you might try importing and going from there--as suggested in the discussion of the second issue linked above.

**Comment by HoseynAAmiri** [comment]
@egoughnour How can I use --root ? Can you make an example please?
